linters-settings:
  errcheck:
    check-type-asserts: true
    check-blank: true
  misspell:
    locale: US

linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      text: "G404:"
      linters:
        - gosec
    - path: _test\.go
      linters:
        - funlen
        - forbidigo
        - varnamelen
