linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - depguard

issues:
  exclude-rules:
    - path: _test\.go
      text: "G404:"
      linters:
        - gosec
    - path: _test\.go
      text: "G115:"
      linters:
        - gosec
    - path: _test\.go
      linters:
        - funlen
        - forbidigo
        - varnamelen
        - depguard
