sudo: false

language: go
go:
- 1.10.x
- 1.11.x
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get -u github.com/golang/dep/cmd/dep golang.org/x/lint/golint honnef.co/go/tools/cmd/megacheck

install:
- dep ensure

before_script:
- go vet . ./base58
- golint -set_exit_status=1 . ./base58
- megacheck . ./base58

script:
- go test -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
