name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '10 10 * * 0'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36.0
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.14.x', '1.15.x' ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test Go Code
        run: go test -covermode=atomic -coverprofile=coverage.txt ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
